/// Mocked data service for Daily Meal Plan
/// Provides realistic meal plan data structured like a real API response
class DailyMealPlanMockService {
  /// Get daily meal plan for a specific date
  static Future<Map<String, dynamic>> getDailyMealPlan(DateTime date) async {
    await Future.delayed(const Duration(milliseconds: 800));

    final dayIndex = date.weekday - 1;
    final plan = _weeklyMealPlan[dayIndex];
    final meals = plan['meals'] as Map<String, dynamic>;

    return {
      'date': date.toIso8601String(),
      'persona': {
        'name': 'Sunita Rao',
        'age': 42,
        'city': 'Bangalore',
        'conditions': ['Type 2 Diabetes', 'Mild Hypertension'],
      },
      'meals': meals,
      'dailySummary': {
        'totalCalories': plan['totalCalories'],
        'targetCalories': 1780,
        'totalCost': plan['totalCost'],
        'budgetLimit': 260.0,
        'totalSodiumMg': plan['totalSodiumMg'],
        'sodiumTargetMg': 1700,
        'budgetStatus': 'within',
      },
      'explainability': {
        'title': 'Why these meals were selected today',
        'reasons': [
          plan['dayNote'],
          'Balanced carbohydrate distribution supports glucose stability through school hours.',
          'Lower-sodium cooking choices may support blood pressure management.',
          'Uses familiar home-style dishes with practical Bangalore grocery pricing.',
        ],
      },
    };
  }

  static const List<Map<String, dynamic>> _weeklyMealPlan = [
    {
      'totalCalories': 1680,
      'totalCost': 228.0,
      'totalSodiumMg': 1510,
      'dayNote':
          'Breakfast was skipped yesterday, so today starts with a higher-fiber breakfast to prevent mid-morning hunger.',
      'meals': {
        'breakfast': {
          'id': 'mon_bf',
          'name': '2 Ragi Dosas + Mint Peanut Chutney',
          'calories': 320,
          'cost': 42.0,
          'time': '8:00 AM',
          'sodiumMg': 290,
          'healthBadge': 'Low glycemic',
          'glycemicNote': 'Millet base slows glucose rise compared with plain rice dosa.',
          'explanation': 'Sustained energy for morning classes with better post-meal sugar control.',
          'image': 'assets/images/meals/2_ragi_dosas_mint_peanut_chutney.png',
          'semanticLabel': 'Homemade ragi dosa with mint peanut chutney on steel plate',
        },
        'midMorning': {
          'id': 'mon_mm',
          'name': '1 Small Guava + 5 Almonds',
          'calories': 110,
          'cost': 32.0,
          'time': '10:45 AM',
          'sodiumMg': 8,
          'healthBadge': 'Fiber support',
          'glycemicNote': 'Pairing fruit with nuts helps blunt glucose spikes.',
          'explanation': 'Portable school-break snack with balanced carbs and fat.',
          'image': 'assets/images/meals/1_small_guava_5_almonds.png',
          'semanticLabel': 'Guava slices with almonds in a bowl',
        },
        'lunch': {
          'id': 'mon_ln',
          'name': 'Brown + White Rice Mix, Sambar, Beans Poriyal, Curd',
          'calories': 470,
          'cost': 68.0,
          'time': '1:15 PM',
          'sodiumMg': 430,
          'healthBadge': 'Balanced plate',
          'glycemicNote': 'Higher fiber lunch selected to improve satiety.',
          'explanation': 'Partial brown-rice swap keeps meal familiar while reducing glycemic load.',
          'image': 'assets/images/meals/brown_white_rice_mix_sambar_beans_poriyal_curd.png',
          'semanticLabel': 'Brown rice with sambar, beans poriyal, and curd on a banana leaf',
        },
        'eveningSnack': {
          'id': 'mon_es',
          'name': 'Roasted Chana Sundal + Lemon',
          'calories': 160,
          'cost': 34.0,
          'time': '5:00 PM',
          'sodiumMg': 120,
          'healthBadge': 'Protein snack',
          'glycemicNote': 'Legume-based snack supports stable evening glucose.',
          'explanation': 'Avoids fried snacks and keeps appetite controlled before dinner.',
          'image': 'assets/images/meals/Roasted Chana Sundal + Lemon.png',
          'semanticLabel': 'Homemade roasted chana sundal with lemon in steel bowl',
        },
        'dinner': {
          'id': 'mon_dn',
          'name': '2 Phulkas + Lauki Chana Dal + Cucumber Salad',
          'calories': 620,
          'cost': 92.0,
          'time': '8:15 PM',
          'sodiumMg': 662,
          'healthBadge': 'Sodium aware',
          'glycemicNote': 'Controlled cereal portion at night reduces overnight glucose variability.',
          'explanation': 'Lighter oil tempering used for blood pressure support.',
          'image': 'assets/images/meals/2 Phulkas + Lauki Chana Dal + Cucumber Salad.png',
          'semanticLabel': 'Phulka with lauki chana dal and salad',
        },
      },
    },
    {
      'totalCalories': 1715,
      'totalCost': 236.0,
      'totalSodiumMg': 1570,
      'dayNote': 'Leftover sambar from Monday lunch is reused at breakfast to reduce waste and cooking time.',
      'meals': {
        'breakfast': {
          'id': 'tue_bf',
          'name': '2 Idlis + Leftover Vegetable Sambar + Flaxseed Chutney',
          'calories': 300,
          'cost': 38.0,
          'time': '7:50 AM',
          'sodiumMg': 310,
          'healthBadge': 'Family-friendly',
          'glycemicNote': 'Fermented batter and dal-rich sambar improve meal quality.',
          'explanation': 'Using leftover sambar saves time on school-day morning.',
          'image': 'assets/images/meals/2 Idlis + Leftover Vegetable Sambar + Flaxseed Chutney.png',
          'semanticLabel': 'Homemade idli with sambar and chutney on steel plate',
        },
        'midMorning': {
          'id': 'tue_mm',
          'name': 'Unsweetened Buttermilk + 1 Tbsp Roasted Peanuts',
          'calories': 95,
          'cost': 26.0,
          'time': '10:40 AM',
          'sodiumMg': 95,
          'healthBadge': 'Hydration support',
          'glycemicNote': 'Low-carb and protein-assisted mini meal.',
          'explanation': 'Helps prevent energy dip between classes.',
          'image': 'assets/images/meals/Unsweetened Buttermilk + 1 Tbsp Roasted Peanuts.png',
          'semanticLabel': 'Glass of buttermilk with peanuts',
        },
        'lunch': {
          'id': 'tue_ln',
          'name': 'Vegetable Millet Pongal + Keerai Kootu + Carrot Kosambari',
          'calories': 480,
          'cost': 74.0,
          'time': '1:10 PM',
          'sodiumMg': 415,
          'healthBadge': 'Fiber-forward',
          'glycemicNote': 'Millet meal chosen for slower carbohydrate release.',
          'explanation': 'Lunch optimized with extra fiber today.',
          'image': 'assets/images/meals/Vegetable Millet Pongal + Keerai Kootu + Carrot Kosambari.png',
          'semanticLabel': 'Millet pongal with greens and salad',
        },//change the image !!!!!
        'eveningSnack': {
          'id': 'tue_es',
          'name': 'Sprouted Moong Chaat (Low Salt)',
          'calories': 170,
          'cost': 40.0,
          'time': '4:45 PM',
          'sodiumMg': 140,
          'healthBadge': 'Protein + fiber',
          'glycemicNote': 'Balanced snack reduces risk of overeating at dinner.',
          'explanation': 'Added lemon and cucumber for flavor instead of extra salt.',
          'image': 'assets/images/meals/Sprouted Moong Chaat (Low Salt).png',
          'semanticLabel': 'Sprouted moong salad in bowl',
        },
        'dinner': {
          'id': 'tue_dn',
          'name': 'Vegetable Oats Adai + Tomato Chutney + Curd',
          'calories': 670,
          'cost': 92.0,
          'time': '8:20 PM',
          'sodiumMg': 610,
          'healthBadge': 'Diabetes aware',
          'glycemicNote': 'Higher protein lentil batter supports glucose stability.',
          'explanation': 'Keeps dinner familiar while reducing refined-carb load.',
          'image': 'assets/images/meals/Vegetable Oats Adai + Tomato Chutney + Curd.png',
          'semanticLabel': 'Adai with tomato chutney and curd',
        },
      },
    },
    {
      'totalCalories': 1665,
      'totalCost': 222.0,
      'totalSodiumMg': 1475,
      'dayNote': 'Sodium intake improved by 11% this week by reducing pickle portions and extra table salt.',
      'meals': {
        'breakfast': {
          'id': 'wed_bf',
          'name': 'Vegetable Broken Wheat Upma + Plain Curd',
          'calories': 315,
          'cost': 42.0,
          'time': '8:05 AM',
          'sodiumMg': 260,
          'healthBadge': 'Steady energy',
          'glycemicNote': 'Dalia-based breakfast gives slower glucose response than refined rava.',
          'explanation': 'Supports concentration during busy mid-week schedule.',
          'image': 'assets/images/meals/Vegetable Broken Wheat Upma + Plain Curd.png',
          'semanticLabel': 'Broken wheat upma with vegetables',
        },
        'midMorning': {
          'id': 'wed_mm',
          'name': '1 Orange + Pumpkin Seeds',
          'calories': 105,
          'cost': 36.0,
          'time': '10:50 AM',
          'sodiumMg': 5,
          'healthBadge': 'Micronutrient boost',
          'glycemicNote': 'Portion-controlled fruit with seeds supports satiety.',
          'explanation': 'Light option to keep lunch appetite moderate.',
          'image': 'assets/images/meals/1 Orange + Pumpkin Seeds.png',
          'semanticLabel': 'Orange wedges with pumpkin seeds',
        },
        'lunch': {
          'id': 'wed_ln',
          'name': 'Red Rice, Rasam, Cabbage Poriyal, Kadalai Sundal',
          'calories': 465,
          'cost': 66.0,
          'time': '1:20 PM',
          'sodiumMg': 395,
          'healthBadge': 'Heart-conscious',
          'glycemicNote': 'Legume side dish improves post-lunch glucose profile.',
          'explanation': 'Extra fiber lunch selected after lower-fiber Tuesday dinner.',
          'image': 'assets/images/meals/Red Rice, Rasam, Cabbage Poriyal, Kadalai Sundal.png',
          'semanticLabel': 'Red rice with rasam and poriyal',
        },
        'eveningSnack': {
          'id': 'wed_es',
          'name': '1 Small Ragi Malt (Unsweetened) + 2 Walnuts',
          'calories': 165,
          'cost': 38.0,
          'time': '5:10 PM',
          'sodiumMg': 68,
          'healthBadge': 'Low sugar',
          'glycemicNote': 'No jaggery added; cinnamon used for flavor.',
          'explanation': 'Warm snack suitable for rainy Bangalore evenings.',
          'image': 'assets/images/meals/1 Small Ragi Malt (Unsweetened) + 2 Walnuts.png',
          'semanticLabel': 'Ragi malt drink with walnuts',
        },
        'dinner': {
          'id': 'wed_dn',
          'name': '2 Jowar Rotis + Mixed Veg Kurma (Less Coconut) + Salad',
          'calories': 615,
          'cost': 94.0,
          'time': '8:10 PM',
          'sodiumMg': 747,
          'healthBadge': 'Portion balanced',
          'glycemicNote': 'Whole-grain roti and non-starchy vegetables reduce glycemic load.',
          'explanation': 'Kept dinner satisfying for whole family without extra oil.',
          'image': 'assets/images/meals/2 Jowar Rotis + Mixed Veg Kurma (Less Coconut) + Salad.png',
          'semanticLabel': 'Jowar roti with vegetable kurma',
        },
      },
    },
    {
      'totalCalories': 1730,
      'totalCost': 242.0,
      'totalSodiumMg': 1595,
      'dayNote': 'A moderate North Indian-style lunch is included for variety while preserving glucose and sodium control.',
      'meals': {
        'breakfast': {
          'id': 'thu_bf',
          'name': 'Pesarattu + Onion Chutney (Low Salt)',
          'calories': 310,
          'cost': 44.0,
          'time': '7:55 AM',
          'sodiumMg': 275,
          'healthBadge': 'Protein breakfast',
          'glycemicNote': 'Moong-based crepe has lower glycemic impact than plain dosa.',
          'explanation': 'Helps avoid mid-morning cravings during teaching hours.',
          'image': 'assets/images/meals/Pesarattu + Onion Chutney (Low Salt).png',
          'semanticLabel': 'Pesarattu with onion chutney',
        },
        'midMorning': {
          'id': 'thu_mm',
          'name': 'Tender Coconut Water + 4 Peanuts',
          'calories': 85,
          'cost': 32.0,
          'time': '10:35 AM',
          'sodiumMg': 40,
          'healthBadge': 'Hydration',
          'glycemicNote': 'Small controlled volume to avoid excess natural sugars.',
          'explanation': 'Useful on warmer days and supports fluid intake.',
          'image': 'assets/images/meals/Tender Coconut Water + 4 Peanuts.png',
          'semanticLabel': 'Tender coconut water',
        },
        'lunch': {
          'id': 'thu_ln',
          'name': '2 Phulkas + Methi Dal + Bhindi Sabzi + Curd',
          'calories': 500,
          'cost': 82.0,
          'time': '1:05 PM',
          'sodiumMg': 430,
          'healthBadge': 'Blood sugar support',
          'glycemicNote': 'Balanced carbohydrate distribution supports glucose stability.',
          'explanation': 'North-style meal kept low-oil and low-sodium for practicality.',
          'image': 'assets/images/meals/2 Phulkas + Methi Dal + Bhindi Sabzi + Curd.png',
          'semanticLabel': 'Phulkas with dal and bhindi',
        },
        'eveningSnack': {
          'id': 'thu_es',
          'name': 'Baked Methi Muthia + Pudina Dip',
          'calories': 180,
          'cost': 44.0,
          'time': '5:00 PM',
          'sodiumMg': 170,
          'healthBadge': 'Baked option',
          'glycemicNote': 'Steamed-baked snack avoids refined and fried items.',
          'explanation': 'Swapped fried tea snack with baked version.',
          'image': 'assets/images/meals/Baked Methi Muthia + Pudina Dip.png',
          'semanticLabel': 'Baked methi snack with mint dip',
        },
        'dinner': {
          'id': 'thu_dn',
          'name': 'Vegetable Sambar Oats + Stir-fried Beans',
          'calories': 655,
          'cost': 86.0,
          'time': '8:00 PM',
          'sodiumMg': 680,
          'healthBadge': 'Night-light',
          'glycemicNote': 'Oats and lentils create slower glucose absorption at dinner.',
          'explanation': 'Soft one-pot dinner reduces late-night cooking effort.',
          'image': 'assets/images/meals/Vegetable Sambar Oats + Stir-fried Beans.png',
          'semanticLabel': 'Savory oats with sambar style vegetables',
        },
      },
    },
    {
      'totalCalories': 1695,
      'totalCost': 231.0,
      'totalSodiumMg': 1525,
      'dayNote': 'End-of-week meals prioritize pantry leftovers to reduce waste and keep grocery spend predictable.',
      'meals': {
        'breakfast': {
          'id': 'fri_bf',
          'name': '2 Small Set Dosas (Millet Mix) + Tomato Onion Chutney',
          'calories': 330,
          'cost': 46.0,
          'time': '8:00 AM',
          'sodiumMg': 300,
          'healthBadge': 'Family-compatible',
          'glycemicNote': 'Millet blend chosen in batter instead of only white rice.',
          'explanation': 'Keeps breakfast familiar for children while improving quality.',
          'image': 'assets/images/meals/2 Small Set Dosas (Millet Mix) + Tomato Onion Chutney.png',
          'semanticLabel': 'Set dosa with tomato chutney',
        },
        'midMorning': {
          'id': 'fri_mm',
          'name': 'Cucumber Sticks + Homemade Hung Curd Dip',
          'calories': 90,
          'cost': 30.0,
          'time': '10:45 AM',
          'sodiumMg': 60,
          'explanation': 'Good hydration and crunch without packaged snacks.',
          'image': 'assets/images/meals/Cucumber Sticks + Homemade Hung Curd Dip.png',
          'semanticLabel': 'Cucumber sticks with curd dip',
        },
        'lunch': {
          'id': 'fri_ln',
          'name': 'Vegetable Bisibelebath (Less Rice, More Dal) + Kosambari',
         'calories': 495,
         'cost': 74.0,
         'time': '1:25 PM',
         'sodiumMg': 455,
         'explanation': 'Traditional Karnataka lunch modified, not replaced.',
         'image': 'assets/images/meals/Vegetable Bisibelebath (Less Rice, More Dal) + Kosambari.png',
         'semanticLabel': 'Bisibelebath with salad',
        },
        'eveningSnack': {
          'id': 'fri_es',
          'name': 'Roasted Makhana (Home Spice Mix)',
          'calories': 145,
          'cost': 42.0,
          'time': '4:50 PM',
          'sodiumMg': 110,
          'healthBadge': 'Low oil',
          'glycemicNote': 'Lower glycemic and lower sodium than chips/mixture.',
          'explanation': 'Uses measured oil spray instead of deep fry.',
          'image': 'assets/images/meals/Roasted Makhana (Home Spice Mix).png',
          'semanticLabel': 'Roasted makhana in bowl',
        },
        'dinner': {
          'id': 'fri_dn',
          'name': '2 Chapatis + Paneer Bhurji (Low Salt) + Sauteed Capsicum',
          'calories': 635,
          'cost': 98.0,
          'time': '8:25 PM',
          'sodiumMg': 600,
          'healthBadge': 'Protein dinner',
          'glycemicNote': 'Higher protein dinner may improve satiety and overnight stability.',
          'explanation': 'Weekend-prep friendly meal with low-cost paneer portioning.',
          'image': 'assets/images/meals/2 Chapatis + Paneer Bhurji (Low Salt) + Sauteed Capsicum.png',
          'semanticLabel': 'Chapati with paneer bhurji',
        },
      },
    },
    {
      'totalCalories': 1750,
      'totalCost': 248.0,
      'totalSodiumMg': 1635,
      'dayNote': 'Saturday includes a slightly indulgent family lunch, balanced with portion control and lower-sodium dinner.',
      'meals': {
        'breakfast': {
          'id': 'sat_bf',
          'name': 'Vegetable Poha + Boiled Chana',
          'calories': 335,
          'cost': 40.0,
          'time': '8:30 AM',
          'sodiumMg': 285,
          'healthBadge': 'Weekend practical',
          'glycemicNote': 'Added chana protein lowers overall glycemic impact.',
          'explanation': 'Quick to prepare before weekend errands.',
          'image': 'assets/images/meals/Vegetable Poha + Boiled Chana.png',
          'semanticLabel': 'Vegetable poha with chana',
        },
        'midMorning': {
          'id': 'sat_mm',
          'name': '1 Small Apple + Cinnamon',
          'calories': 95,
          'cost': 34.0,
          'time': '11:00 AM',
          'sodiumMg': 3,
          'healthBadge': 'Portion aware',
          'glycemicNote': 'Single small fruit serving to keep carbs distributed.',
          'explanation': 'Helps spacing carbs across the day.',
          'image': 'assets/images/meals/1 Small Apple + Cinnamon.png',
          'semanticLabel': 'Sliced apple with cinnamon',
        },
        'lunch': {
          'id': 'sat_ln',
          'name': 'Vegetable Pulao (Brown+White Mix) + Rajma + Onion Raita',
          'calories': 530,
          'cost': 96.0,
          'time': '1:30 PM',
          'sodiumMg': 500,
          'healthBadge': 'Family weekend meal',
          'glycemicNote': 'Mixed-rice approach reduces glycemic load without changing family menu.',
          'explanation': 'North Indian lunch for variety while maintaining balance.',
          'image': 'assets/images/meals/Vegetable Pulao (Brown+White Mix) + Rajma + Onion Raita.png',
          'semanticLabel': 'Vegetable pulao with rajma',
        },
        'eveningSnack': {
          'id': 'sat_es',
          'name': 'Masala Corn (No Butter, Less Salt)',
          'calories': 185,
          'cost': 42.0,
          'time': '5:15 PM',
          'sodiumMg': 190,
          'healthBadge': 'Street-style smarter',
          'glycemicNote': 'Balanced with lemon and cucumber to increase volume.',
          'explanation': 'Healthy adaptation of common evening craving.',
          'image': 'assets/images/meals/Masala Corn (No Butter, Less Salt).png',
          'semanticLabel': 'Masala corn in cup',
        },
        'dinner': {
          'id': 'sat_dn',
          'name': 'Lemon Coriander Soup + 2 Moong Dal Chillas',
          'calories': 605,
          'cost': 88.0,
          'time': '8:20 PM',
          'sodiumMg': 657,
          'healthBadge': 'Lighter dinner',
          'glycemicNote': 'Lower-carb dinner after heavier lunch supports daily balance.',
          'explanation': 'Intentional evening light meal after higher-calorie lunch.',
          'image': 'assets/images/meals/Lemon Coriander Soup + 2 Moong Dal Chillas.png',
          'semanticLabel': 'Moong chilla with soup',
        },
      },
    },
    {
      'totalCalories': 1675,
      'totalCost': 219.0,
      'totalSodiumMg': 1480,
      'dayNote': 'Sunday meal prep focuses on next-week readiness with batter prep and chopped vegetables.',
      'meals': {
        'breakfast': {
          'id': 'sun_bf',
          'name': 'Vegetable Rava Idli (Half Rava, Half Oats) + Sambar',
          'calories': 325,
          'cost': 44.0,
          'time': '8:40 AM',
          'sodiumMg': 295,
          'healthBadge': 'Prep-friendly',
          'glycemicNote': 'Oats blend lowers glycemic impact versus plain rava idli.',
          'explanation': 'Supports Sunday batch-cooking routine for weekdays.',
          'image': 'assets/images/meals/Vegetable Rava Idli (Half Rava, Half Oats) + Sambar (2).png',
          'semanticLabel': 'Vegetable idli with sambar',
        },
        'midMorning': {
          'id': 'sun_mm',
          'name': 'Papaya Bowl + 1 tsp Chia Seeds',
          'calories': 105,
          'cost': 34.0,
          'time': '11:00 AM',
          'sodiumMg': 4,
          'healthBadge': 'Digestive support',
          'glycemicNote': 'Fiber helps moderate glucose response.',
          'explanation': 'Light and economical fruit option this week.',
          'image': 'assets/images/meals/Papaya Bowl + 1 tsp Chia Seeds.png',
          'semanticLabel': 'Papaya bowl with chia',
        },
        'lunch': {
          'id': 'sun_ln',
          'name': 'Avarekalu Saaru + 2 Small Ragi Balls + Beetroot Palya',
          'calories': 490,
          'cost': 72.0,
          'time': '1:40 PM',
          'sodiumMg': 420,
          'healthBadge': 'Traditional Karnataka',
          'glycemicNote': 'Ragi portion measured to keep carbohydrates controlled.',
          'explanation': 'Local seasonal avarekalu selected as cheaper protein source.',
          'image': 'assets/images/meals/Avarekalu Saaru + 2 Small Ragi Balls + Beetroot Palya.png',
          'semanticLabel': 'Ragi balls with avarekalu saaru',
        },
        'eveningSnack': {
          'id': 'sun_es',
          'name': 'Homemade Baked Vegetable Cutlet + Green Chutney',
          'calories': 170,
          'cost': 40.0,
          'time': '5:05 PM',
          'sodiumMg': 145,
          'healthBadge': 'Baked snack',
          'glycemicNote': 'Baking lowers fat load and supports Sunday activity.',
          'explanation': 'Uses leftover vegetables from weekly stock.',
          'image': 'assets/images/meals/Homemade Baked Vegetable Cutlet + Green Chutney.png',
          'semanticLabel': 'Baked vegetable cutlets',
        },
        'dinner': {
          'id': 'sun_dn',
          'name': 'Tomato Millet Bath + Cucumber Raita + Sauteed Greens',
          'calories': 585,
          'cost': 80.0,
          'time': '8:10 PM',
          'sodiumMg': 616,
          'healthBadge': 'Week-reset meal',
          'glycemicNote': 'Millet dinner helps improve next-morning fasting trend.',
          'explanation': 'Simple one-pot dinner keeps Sunday cooking stress low.',
          'image': 'assets/images/meals/Tomato Millet Bath + Cucumber Raita + Sauteed Greens.png',
          'semanticLabel': 'Millet tomato bath with raita',
        },
      },
    },
  ];
}
